
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

  [functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-emails"
pinned_version = "1"

  [plugins.inputs]

[build]
command = ""
publish = "."

  [build.environment]
  NODE_VERSION = "20"
  PRERENDER_ENABLE = "true"

  [build.processing]
    skip_processing = false

# Prerender Redirects for Search Engine Crawlers & Social Bots
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200