
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

  [functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-emails"
pinned_version = "1"

  [plugins.inputs]

[build]
command = ""
publish = "."


  [build.environment]
  NODE_VERSION = "20"

  [build.processing]
    skip_processing = true


  [build.services]